package com.tnt.food_delivery.core.utils

object NavDestinations {
    const val SPLASH_SCREEN = "SPLASH_SCREEN"
    const val SIGNIN_SCREEN = "SIGNIN_SCREEN"
    const val SIGNUP_SCREEN = "SIGNUP_SCREEN"
    const val SIGNUP_PROCESS_SCREEN = "SIGNUP_PROCESS_SCREEN"
    const val UPLOAD_PHOTO_SCREEN = "UPLOAD_PHOTO_SCREEN"
    const val SIGNUP_SUCCESS_SCREEN = "SIGNUP_PROCESS_SCREEN"
    const val MAIN_SCREEN = "MAIN_SCREEN"
    const val SETTING_SCREEN = "SETTING_SCREEN"
    const val FILTER_SCREEN = "FILTER_SCREEN"
    const val PRODUCT_DETAIL_SCREEN = "PRODUCT_DETAIL_SCREEN"
    const val RESTAURANT_DETAIL_SCREEN = "RESTAURANT_DETAIL_SCREEN"
}